### DISCUSSION TITLE
Share & Show Off your custom Room Summary cards here!

### DISCUSSION THREAD

**Discussion by warmfire540** [homeassistant-extras/room-summary-card#109] [Show and tell]
We want to see cool things you've done with `room-summary-card`!

**Comment by ma-gu-16** [comment]
Kinda default :)
![image](https://github.com/user-attachments/assets/96b6dcb1-6649-49b4-9818-de32838f0f6d)


`
styles:
  title:
    font-size: 18px;
    font-weight: bold;
  card:
    min-height: 165px;
    max-height: 165px;
  sensors:
    font-size: 15px;
  entities:
    grid-template-rows: 1fr 1fr 1fr !important;
    aspect-ratio: 0.27 / 1 !important;
    padding-right: 0 !important;
`

**Comment by anandv85** [comment]
This is one of my favourite card!
![image](https://github.com/user-attachments/assets/da62871b-d2bc-4676-96de-937164bcff6d)

**Reply by posreg** [reply]
do you have main entity for the room ? i;m kind of struggling, how to assign icon and color just without any entity.ANy chance you can share your setup please :)?

**Reply by warmfire540** [reply]
@posreg you don't need to assign a main entity, not all my rooms have one, only the ones with smart lights.

**Reply by posreg** [reply]
> @posreg you don't need to assign a main entity, not all my rooms have one, only the ones with smart lights.

thank you! can you then point me which CSS/style option you are using to set the icon and its color for those rooms without main entity :)?

**Reply by warmfire540** [reply]
here's some css you _could_ do w/ not entity.  maybe not supported, but it works..

```yaml
type: custom:room-summary-card
area: attic
styles:
  entity_icon:
    "--state-light-inactive-color": blue
entities:
  - input_boolean.gina_mute
```

<img width="575" height="568" alt="Screenshot 2025-10-16 at 8 36 21 PM" src="https://github.com/user-attachments/assets/b07a3b4b-c4ed-424b-bb76-80fa20013107" />

**Comment by warmfire540** [comment]
Mine is pretty default too - just testing some scenarios

<img width="1649" height="628" alt="image" src="https://github.com/user-attachments/assets/35fa134e-50aa-4f2f-a04c-17537cd944a5" />

Random styles I was testing to see what's possible

<img width="1290" height="925" alt="image" src="https://github.com/user-attachments/assets/bb02c99f-9781-4422-bc24-ed7d72f2e1a7" />

**Reply by kaptainen** [reply]
Looks absolutely amazing, was wondering, is it possible to have album art from a media player shown where you have the t-shirt-promo.png in the Dining Room card?

**Reply by warmfire540** [reply]
@kaptainen yeah, in the backgrounds section you can pick an entity w/ `entity_picture` attribute, I assume media players would set this.  or template an entity for this and it'll change as the songs change

**Reply by kaptainen** [reply]
The latest update.. thanks 👍

**Reply by warmfire540** [reply]
@kaptainen lemme see - you got some album art showing now?

**Reply by kaptainen** [reply]
![Screenshot_2025-10-24-13-21-48-89_200b0a05dbc45b1de60d6a2da09c9fd1](https://github.com/user-attachments/assets/a11b673b-ed72-400a-9cfa-126a275cf16d)

**Comment by st0n1-boop** [comment]
<img width="1415" height="260" alt="image" src="https://github.com/user-attachments/assets/9fa066e6-2e68-46d7-9de6-55e2ea1b6eb2" />
 
This is how I have it right now - I'm just wondering how I can control the opacity and color of the entities independet from each other. As you can see in the kitchen, it becomes it bit more difficult with a darker background, and having opacity at 1 makes icon and icon_container idistinguishable from one another.

**Reply by warmfire540** [reply]
@st0n1-boop what's your yaml for one of those as a start, I can see what's controllable or not, it may be semi-limited atm

**Reply by st0n1-boop** [reply]
@warmfire540 below is the yaml for one of those cards.
```
type: custom:room-summary-card
area: badezimmer
background:
  image: /local/images/Raum_Bad1.png
  opacity: 70
features:
  - hide_area_stats
  - hide_room_icon
  - exclude_default_entities
sensors:
  - sensor.tempfeucht_badezimmer_temperature
  - sensor.tempfeucht_badezimmer_humidity
entities:
  - entity_id: switch.lichtschalter_badezimmer_left
    on_color: warm_white
    off_color: black
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - entity_id: switch.lichtschalter_badezimmer_right
    on_color: warm_white
    off_color: black
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - entity_id: sensor.thermostat_badezimmer_onoff
    on_color: red
    off_color: black
    tap_action:
      action: none
    hold_action:
      action: none
styles:
  card:
    background: none
    border-radius: 50px
    aspect-ratio: 16/9
    box-shadow: 0 4px 8px rgba(0,0,0,0.2)
    text-shadow: 0 0 10px rgba(0, 0, 0, 0.8)
    text-transform: uppercase
  title:
    color: rgba(255, 255, 255, 0.8)
    font-size: 2em
    font-weight: bold
  sensors:
    color: rgba(255, 255, 255, 1)
    "--user-sensor-icon-size": 25px
  entity_icon:
    width: 50%
    transform: scale(2)
    "--opacity-icon-fill-inactive": 0.3
    "--opacity-icon-fill-active": 0.3
    padding: 10px
```
