### DISCUSSION TITLE
Configuring Custom Actions for Entities

### DISCUSSION THREAD

**Discussion by Erikkyw** [homeassistant-extras/room-summary-card#141] [Ideas]
I would like to choose what happens after tapping a entity icon on the card.
For example if i press a climate entity i would like to see the "more-info" tap action

**Comment by anandv85** [comment]
Also, when I click on the main room icon (bottom left), I prefer to toggle the entity rather than navigating to a path.

**Comment by warmfire540** [comment]
@Erikkyw @anandv85 this is doable - you will just need to configure this via yaml, not the editor

Here's an issue related to this: https://github.com/homeassistant-extras/room-summary-card/issues/114

Here's some docs
- https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/ACTION-CONFIGURATION.md
- https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/ENTITY-CONFIGURATION.md#entity-configuration-options
- https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/EXAMPLES.md#full-configuration-example

Here's examples of how to configure

```yaml
type: custom:room-summary-card
area: living_room
entity:
  entity_id: light.living_room_main
  icon: mdi:ceiling-light
  tap_action:
    action: toggle
  hold_action:
    action: more-info
entities:
  - entity_id: switch.living_room_tv
     icon: mdi:television
     tap_action:
       action: more-info
     hold_action:
       action: navigate
  - light.living_room_lamp
  - switch.living_room_fan
```
