### DISCUSSION TITLE
How to show more than 4 entities (or 2 columns)

### DISCUSSION THREAD

**Discussion by ArLo69** [homeassistant-extras/room-summary-card#142] [Q&A]
Hello,

I want to display more than 4 entities. I can add them, but the fifth one is only partially visible, no matter what I try.
To my understanding, the aspect-ratio I use makes the card wide enough to show two columns of entities.
The grid options should show two columns of 4 entities.
But I only get one, and the fifth entity is below the fourth one and only partially visible. 
Can anyone tell what I am doing wrong or give a suggestion how to show all entities?
> styles:
  card:
    aspect-ratio: 2/1
  entities:
    grid-template-columns: 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr 1fr;

**Comment by warmfire540** [comment]
Hey!

yeah this is doable, you may need to use `!important` - I have updated the READMEs to reflect.  See these issues for examples
- https://github.com/homeassistant-extras/room-summary-card/issues/131
- https://github.com/homeassistant-extras/room-summary-card/issues/144
- https://github.com/homeassistant-extras/room-summary-card/issues/108

```yaml
type: custom:room-summary-card
area: attic
styles:
  entities:
    grid-template-columns: 1fr 1fr !important
```

**Reply by NEPAGitmo** [reply]
Just found your card. Definitely will improve WAF. Is there any way to get two columns of full size icons by shrinking the room entity icon area?

**Reply by warmfire540** [reply]
if you understand grid system, you could change the layout and give entities a larger section potentially

**Reply by NEPAGitmo** [reply]
Unfortunately I don't but I'm trying to learn.

**Reply by warmfire540** [reply]
what's your current yaml, I'll try and play around with it and see if I can cook something up

**Comment by NEPAGitmo** [comment]
Thanks for responding. Here is the YAML, appreciate you taking a look.

```
type: custom:room-summary-card
area: kitchen
styles:
  entities:
    grid-template-columns: 1fr 1fr !important;
  entity_icon:
    transform: scale(1.12)
entity:
  entity_id: switch.kitchen_do_not_disturb
  on_color: ""
  off_color: ""
  label: Do Not Disturb
  tap_action:
    action: more-info
  double_tap_action:
    action: none
features:
  - show_entity_labels
  - hide_area_stats
  - skip_climate_styles
  - exclude_default_entities
entities:
  - entity_id: light.ceiling
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - entity_id: switch.hutch
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - entity_id: switch.microwave
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - entity_id: switch.sink
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - entity_id: switch.electric_kettle_lite_power_switch
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
    label: Tea Kettle
  - entity_id: switch.plant_light
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - entity_id: switch.refrigerator_express_mode
    on_color: ""
    off_color: ""
    double_tap_action:
      action: none
    hold_action:
      action: more-info
    label: Quick Ice
sensors:
  - binary_sensor.ceiling_motion_detection
  - binary_sensor.refrigerator_door
  - sensor.kitchen_next_timer
```
