### ISSUE TITLE
Icon Color & threshold

### ISSUE THREAD

**Issue by ma-gu-16** [homeassistant-extras/room-summary-card#100]
Hi, 

i just try the room card. 

i try to set active icon color but it doesnt work, same for on_color: 

```
entities:
  - entity_id: switch.brunnen
    icon: mdi:sprout
    icon_color: |
      {% if is_state('switch.brunnen', 'on') %}
        green
      {% endif %}
```

next room, i want to use the threshold but in one area there are multiple temp sensors. 
and the average is just not "correct". for example: roomtemp + 3dprinter temp = way to high avarage temp. 

is used the customs sensors. but how can i make the threshold work with a specified sensor. 

```
thresholds:
  temperature: 27
  humidity: 41
features:
  - hide_area_stats
  - exclude_default_entities
sensors:
  - sensor.thermostat_buro_temperatur
  - sensor.thermostat_buro_luftfeuchtigkeit
  - sensor.buro_absolute_luftfeuchtigkeit
```

thanks for any help.

**Comment by warmfire540** [comment]
@ma-gu-16 if you use HomeAssistants built in area card, what is it showing?

as a workaround for now, you can manually set "sensor_classes" to not have temperature as a choice, and then it'll just use sensors.  

not sure if it'll average the ones you set on "sensors" array, I'll have to check that...

this is a good edge case, didn't think of this

**Comment by warmfire540** [comment]
@ma-gu-16 `icon_color` isn't a property you can set on the card, however you can now set on & off colors: https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/ENTITY-ATTRIBUTES.md

`icon_color` is something that is set by a third party integration, but no need for it if you use on/off colors.

**Comment by ma-gu-16** [comment]
> [@ma-gu-16](https://github.com/ma-gu-16) `icon_color` isn't a property you can set on the card, however you can now set on & off colors: https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/ENTITY-ATTRIBUTES.md
> 
> `icon_color` is something that is set by a third party integration, but no need for it if you use on/off colors.

i tried different. i use the third party integration but it doesnt work. on/off_ colors. too. no success.


```
type: custom:room-summary-card
area_name: Büro
name: Büro
navigate: /lovelace/buero
entity:
  entity_id: light.dimmer_buro_aktor
  icon: mdi:laptop-account
entities:
  - entity_id: light.dimmer_buro_aktor
    icon: mdi:lightbulb-on
  - entity_id: light.buro_schrank_ledstrip
    icon: mdi:led-strip-variant
  - entity_id: switch.3d_drucker
    icon: mdi:printer-3d-nozzle
    tap_action:
      action: more-info
sensor_layout: stacked
area: buro
thresholds:
  temperature: 27
  humidity: 41
features:
  - hide_area_stats
  - exclude_default_entities
sensors:
  - sensor.thermostat_buro_temperatur
  - sensor.thermostat_buro_luftfeuchtigkeit
  - sensor.buro_absolute_luftfeuchtigkeit
card_mod:
  style: |
    ha-card {
      min-height: 165px;
      max-height: 165px;
    }
    .sensors.text {
      font-size: 15px;
    }
    .name.text {
      font-size: 18px;
      font-weight: bold;
    }
    .entities-container{
      grid-template-rows: 1fr 1fr 1fr !important;
    }

```

and the humidity and temp icons does not show. i can use, the area default entities or i disable and use my own sensors. no icon. 



 

> [@ma-gu-16](https://github.com/ma-gu-16) if you use HomeAssistants built in area card, what is it showing?
> 
> as a workaround for now, you can manually set "sensor_classes" to not have temperature as a choice, and then it'll just use sensors.
> 
> not sure if it'll average the ones you set on "sensors" array, I'll have to check that...
> 
> this is a good edge case, didn't think of this

same. i get an avareage of all temperatures. 

EDIT:
the default area card from homeassistant has the same problem:

for example if i use the homeassistant mold indicator. 

![Image](https://github.com/user-attachments/assets/3b9183df-9417-47f0-8ee0-d04dfa0d8c6f)

i get the average of 58% and 100%  as humidity.  thats wrong.  i only want to display the humidity and the threshold on that.

**Comment by ma-gu-16** [comment]
i dont know why, but after i add an homeassistant area card, the icons are visible on all room-cards. 
when i remove the areacard and refresh the page, the icons are gone.

**Comment by ma-gu-16** [comment]
> [@ma-gu-16](https://github.com/ma-gu-16) `icon_color` isn't a property you can set on the card, however you can now set on & off colors: https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/ENTITY-ATTRIBUTES.md
> 
> `icon_color` is something that is set by a third party integration, but no need for it if you use on/off colors.

ok icon color works now with latest update today. it would be awesome if its possible to use functions inside the color management like "icon_color" third party. or make it possible to use icon_color.

**Comment by warmfire540** [comment]
@ma-gu-16 you should be able to use templates today.  icon_color can be replaced by on/off colors.

see this post: https://github.com/homeassistant-extras/room-summary-card/issues/63#issuecomment-2940336801

let me know if there are tweaks we need to make to the card

**Comment by ma-gu-16** [comment]
```
type: custom:room-summary-card
area_name: Büro
name: Büro
navigate: /lovelace/buero
entity:
  entity_id: light.dimmer_buro_aktor
  icon: mdi:laptop-account
entities:
  - entity_id: light.dimmer_buro_aktor
    icon: mdi:lightbulb-on
    on_color: >
      {% set rgb = state_attr('light.philips_hue_iris', 'rgb_color') %}
      {% if (states('light.dimmer_buro_aktor')) == 'on' %}
        #{{ '%02x%02x%02x' | format(rgb[0], rgb[1], rgb[2]) }}
      {% endif %}
  - entity_id: light.buro_schrank_ledstrip
    icon: mdi:led-strip-variant
  - entity_id: switch.3d_drucker
    icon: mdi:printer-3d-nozzle
    tap_action:
      action: more-info
```


i tried this, but wont work

**Comment by warmfire540** [comment]
looking at other cards.. it looks like i'd need to implement the ability for you to supply a template.  is that the ultimate goal?  you'd like to set some of these properties based on templates?

**Comment by ma-gu-16** [comment]
it was just a quick example, i want to set different on_color states depending on "other" states value.

For example, if a switch/meter socket is switched on, you could tell from its color whether and how much power it's drawing. A kind of "traffic light."

**Comment by warmfire540** [comment]
okkk, i'll eyeball templates support.  if it were me though I'd just make a templated sensor so that way the icons and colors and stuff show up all over, not just on the room card.

**Comment by ma-gu-16** [comment]
I think the bigger bug or problem is the threshold on the average room sensors instead of a specified.

**Comment by warmfire540** [comment]
> I think the bigger bug or problem is the threshold on the average room sensors instead of a specified.

it was specifically requested that the threshold be on the average, people said it wouldn't make sense.  as a workaround, can you disable the averaging for that sensor, and just include the single one that "rules them all"?

**Comment by ma-gu-16** [comment]
i would make it by option.  if nothing is set and threshold active it takes the average of the area.
but if you configure maybe an entity_id  it will take this. 

e.g. 
```


area: buro
thresholds:
  temperature: 27
  temperature_entity_id: sensor.thermostat_buro_temperatur
  humidity: 41
  humidity_entity_id: sensor.thermostat_buro_luftfeuchtigkeit
features:
  - hide_area_stats
  - exclude_default_entities
sensors:
  - sensor.thermostat_buro_temperatur
  - sensor.thermostat_buro_luftfeuchtigkeit
  - sensor.buro_absolute_luftfeuchtigkeit


```

**Comment by warmfire540** [comment]
ok that's pretty sleek... won't require workaround.  that should't be too hard

so to be clear... this entity would only trigger thresholds for highlighting borders to show an issue, but the sensor value itself will still be averaged?

in this example
- `sensor.thermostat_buro_temperatur` is 40 degrees
- `sensor.thermostat_buro_luftfeuchtigkeit` is 10 degrees
the threshold WILL be hit, the border will show red that it's too hot, however the temperature sensor will show `25`

**Comment by ma-gu-16** [comment]
my code, i disabled the default entities, and used my own. but yes default entities can still be avarage. like the default threshold. 

if you add an temperature_entity_id, it will check the 27 dreg vs sensor.thermostat_buro_temperatur and if its higher, it shows the border. as soon as an temperature_entity_id exist the average is disabled. 


i mean everyone could still add an own sensor and count as many sensors they like, maybe from different areas.

**Comment by warmfire540** [comment]
OK, going to push this today.. here's what it does

my average is 89, my threshold is 100 - so no borders
<img width="1303" alt="Image" src="https://github.com/user-attachments/assets/5f8a559a-8662-47e4-9bb0-7235b40ca674" />

I set the "trigger" entity to my 100 degree one, now it triggers border (average still 89)
<img width="1308" alt="Image" src="https://github.com/user-attachments/assets/cb03d33a-adae-4f1a-9505-2566e6d659ca" />

**Comment by ma-gu-16** [comment]
exactly what im looking for. cant wait to receive the update :)

**Comment by warmfire540** [comment]
give it a whirl

**Comment by ma-gu-16** [comment]
> give it a whirl

just tried, doesnt work for me :( 
```

    thresholds:
      temperature: 20
      temperature_entity: sensor.thermostat_buro_temperatur
      humidity: 50
      humidity_entity: sensor.thermostat_buro_luftfeuchtigkeit
    
```

**Comment by ma-gu-16** [comment]
Maybe because of the 
      - exclude_default_entities

?

**Comment by warmfire540** [comment]
what's your whole config look like?  these entities would need to not be mentioned for example in "sensors" list

**Comment by ma-gu-16** [comment]
> what's your whole config look like? these entities would need to not be mentioned for example in "sensors" list
```

type: custom:room-summary-card
area_name: Büro
name: Büro
navigate: /lovelace/buero
entity:
  entity_id: light.dimmer_buro_aktor
  icon: mdi:laptop-account
entities:
  - entity_id: light.dimmer_buro_aktor
    icon: mdi:lightbulb-on
  - entity_id: light.buro_schrank_ledstrip
    icon: mdi:led-strip-variant
  - entity_id: switch.3d_drucker
    icon: mdi:printer-3d-nozzle
    tap_action:
      action: more-info
sensor_layout: default
area: buro
thresholds:
  temperature: 20
  temperature_entity: sensor.thermostat_buro_temperatur
  humidity: 50
  humidity_entity: sensor.thermostat_buro_luftfeuchtigkeit
features:
  - hide_area_stats
  - exclude_default_entities
sensors:
  - sensor.thermostat_buro_temperatur
  - sensor.thermostat_buro_luftfeuchtigkeit
  - sensor.empfehlung_zum_luften_buro
styles:
  title:
    font-size: 18px;
    font-weight: bold;
  card:
    min-height: 165px;
    max-height: 165px;
  sensors:
    font-size: 15px;
  entities:
    grid-template-rows: 1fr 1fr 1fr !important;
    aspect-ratio: 0.27 / 1 !important;
    padding-right: 0 !important;


```

**Comment by ma-gu-16** [comment]
> what's your whole config look like? these entities would need to not be mentioned for example in "sensors" list

i need them in sensors, because i cant use the average room temp.  otherwise i had no temp/hum on the card.

why should it not be mentioned ? whats the reason ? 

greetings :)

**Comment by warmfire540** [comment]
as of now, only the averaged sensors are considered for thresholds. how come the temp humidity isn't showing up automatically?  are the device_classes set on these entities?  are they in the area?

**Comment by ma-gu-16** [comment]
i cant use the average, because i have multiple sensors in that room. for example 3d printer, every of the sensor in this room has correct classes, thats the problem. 


this is why im looking for custom sensors, as i currently use. that works great. 

and custom threashold. so i can set the sensor to monitor. 


i just want to pick 1 temp sensor to display and threshold (border) and the same for humidity

**Comment by warmfire540** [comment]
@ma-gu-16 alright - got the card to look at individual sensors too.  so if you just add the sensor and say it's the one to look at, now it'll trigger

```yaml
type: custom:room-summary-card
area: shed
sensors:
  - sensor.attic_climate_air_temperature # this state is currently "100"
thresholds:
  temperature_entity: sensor.attic_climate_air_temperature # we're looking at that entity, not averaged ones (if existing)
  temperature: 99. # this will trigger now
sensor_classes:
  - battery # i turned off "temperature" since i don't want to see those averaged
```

<img width="1042" alt="Image" src="https://github.com/user-attachments/assets/59f88879-3ca2-4a7c-9bd9-227e5b438243" />
