### ISSUE TITLE
navigate feature not working

### ISSUE THREAD

**Issue by rickd1994** [homeassistant-extras/room-summary-card#105]
Hi, I've encountered an issue where using the feature:

```
features:
  - hide_room_icon
```

causes the navigation action to stop working when tapping the card. However, when I disable this feature and the icon is visible, the navigation works correctly.

Is there something wrong with my YAML configuration, or is this feature not compatible with the navigation action?

```
type: custom:room-summary-card
area: woonkamer
features: 
  - hide_room_icon
background:
  image: /local/woonkamer.png
  opacity: 40
entities:
  - light.staande_hoeklamp_woonkamer
  - light.hoekspot_woonkamer
  - light.rotan_wandlamp_woonkamer
  - light.wandlampen_beneden
entity:
  entity_id: light.verlichting_woonkamer
  double_tap_action:
    action: toggle
grid_options:
  columns: 6
  rows: auto
tap_action:
  action: navigate
  navigation_path: /dashboard-mobiel/woonkamer
```
