### ISSUE TITLE
[Feature Request] The ability to have more than 4 side entities?

### ISSUE THREAD

**Issue by djmaxwell1975** [homeassistant-extras/room-summary-card#131]
while you can select more than 4, i cannot seem to get them to display. Great work though

**Comment by warmfire540** [comment]
hey - you can add this styling:

```yaml
type: custom:room-summary-card
area: attic
styles:
  entities:
    grid-template-columns: 1fr 1fr !important
```

here's example issue where we demonstrate this: https://github.com/homeassistant-extras/room-summary-card/issues/108#issuecomment-2971342771

here's some docs: https://github.com/homeassistant-extras/room-summary-card/blob/main/docs/configuration/CUSTOM-STYLES.md#basic-usage
