### ISSUE TITLE
[Feature Request] Theming - Consolidated, Sharable, Portable Templates

### ISSUE THREAD

**Issue by Ltek** [homeassistant-extras/room-summary-card#138]
For room-summary, if you consolidated the visuals and options into a single section then we could easily copy/paste that into new cards and automatically get the theme we need. For example, below is YAML from one of my cards. Note how the visual settings are embedded with the 'item' it modifies. This make is very challenging to ensure all cards are the same... and harder to share. But what if all theme settings were in a single header

*Current YAML*

```
styles:
  card:
    "--user-card-icon-size": 50%
  sensors:
    "--user-sensor-icon-size": 30px
  entities:
    "--user-entity-icon-size": 44px
occupancy:
  entities:
    - binary_sensor.sensor_living_room_bosch_motion_lr_kitchen_occupancy
    - binary_sensor.home_motion
  card_border_color: "#078fe4"
  options:
    - disable_icon_animation
    - disable_icon_styles
background:
  options:
    - icon_background
  image_entity: camera.living_room_cam_live_view
  opacity: 20
```

*Theme example YAML* -- note all I did was keep the same format/syntax structure and removed the entities themselves (entities: and image-entity:). I moved all non-entity info under 'theme'... which gets merged with the matching headers that contain the entities (in a different section) on rendering.

```
theme:
  styles:
    card:
      "--user-card-icon-size": 50%
    sensors:
      "--user-sensor-icon-size": 30px
    entities:
      "--user-entity-icon-size": 44px
    occupancy:
      entities:
      card_border_color: "#078fe4"
      options:
        - disable_icon_animation
        - disable_icon_styles
    background:
      options:
        - icon_background
      opacity: 20
```
