### ISSUE TITLE
Most Cards not Showing the Room Name

### ISSUE THREAD

**Issue by tardis89** [homeassistant-extras/room-summary-card#14]
I have a weird issue where only a select few of my rooms actually show the title in the room-summary-card.

Works:
```yaml
type: custom:room-summary-card
area: man_cave
entity: light.man_cave
features:
  - hide_area_stats
grid_options:
  rows: auto
  columns: 4
```

![Image](https://github.com/user-attachments/assets/69a9629c-106e-4ef0-8e66-71bd0ffe4037)

Does not work:
Even when I remove the entities, temperature_sensor, and humidity_sensor values, it still does not display the room name.
```yaml
type: custom:room-summary-card
area: living_room
entity: light.lutron_living_room
entities:
  - binary_sensor.living_room_motion_detector
  - light.mantle
  - switch.living_room_ceiling_fan
temperature_sensor: sensor.nest_temperature
humidity_sensor: sensor.nest_humidity
grid_options:
  columns: 4
  rows: auto
```
![Image](https://github.com/user-attachments/assets/e2bec5ce-0220-4131-904c-f34109d48243)
