### ISSUE TITLE
Navigate to... does not work once main entity is specified in a card

### ISSUE THREAD

**Issue by LE-tarantino** [homeassistant-extras/room-summary-card#33]
Hi there, 

while further exploring I found another behaviour that might not be intended: I would like to use the room summary card to jump into the respective area section. I am using the navigate path to indicate the target dashboard URL. But as soon as I specify a main entity for that card (e.g. to indicate any activity in the room) I wont be redirected to the respective dashboard any longer, but will presented with the details of the main entity instead.

YAML for a sample card - **does allow to navigate** on tapping the card - but obviously **does not change color** according to a certain status
```
type: custom:room-summary-card
area: freddy
features:
  - hide_area_stats
  - exclude_default_entities
temperature_sensor: sensor.raumtemperatur_freddy
humidity_sensor: sensor.luftfeuchtigkeit_freddy
grid_options:
  columns: 6
  rows: auto
navigate: /dashboard-home/freddy
```

**YAML for a sample card - **does not allow to navigate** on tapping the card but **does color change** according to status of the main entity**
```
type: custom:room-summary-card
area: freddy
features:
  - hide_area_stats
  - exclude_default_entities
temperature_sensor: sensor.raumtemperatur_freddy
humidity_sensor: sensor.luftfeuchtigkeit_freddy
grid_options:
  columns: 6
  rows: auto
navigate: /dashboard-home/freddy
entity: switch.zentral_freddy
```

**So my request would be, to allow both:** Present a color coding / status of the main entity while preserving the ability to navigate to another dashboard  page when tapping. For sub entities this is coverd by the various actions available for tap, douple tap and hold. However, for the main entity it seems that there is no such option.

Thank you for conidering!
Robert
