### ISSUE TITLE
Navigation path

### ISSUE THREAD

**Issue by ChristopherLMiller** [homeassistant-extras/room-summary-card#37]
right now the navigation path only seems to accept straight URL's.  Would be useful to allow for #path as well so that its compatible with like button cards that use # for popups.  Currently unable to use due to it

**Comment by warmfire540** [comment]
@ChristopherLMiller for me I can do paths with hashtags or query parameters (for like anchor card usage)

can you show where it's not working and I'll do some digging

examples i tried
-  /the-matrix/network?anchor=disconnected
-  /the-matrix/network#foobar

<img width="402" alt="Image" src="https://github.com/user-attachments/assets/bc5c0206-6b38-494c-a7e1-63b617154d3f" />

**Comment by ChristopherLMiller** [comment]
So for bubble card instead of a path just doing like #living_room will popup the bubble card for living room.    I have a singular dashboard with just a single view in it and use bubble card, using the # alone says invalid URL but putting down anyways it won't pop it up

**Comment by warmfire540** [comment]
ok let me check out bubble card and see what I need to do differently

**Comment by warmfire540** [comment]
@ChristopherLMiller there was a bug that was fixed in the last version.  I installed bubble card and tested that setting a navigation path makes bubble card pop up.

here was my config for the my dash w/ bubble and room summary

```yaml
- type: vertical-stack
  cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#kitchen'
      name: Kitchen
      icon: mdi:fridge
      entity: light.office
- type: custom:bubble-card
  card_type: button
  button_type: name
  name: Kitchen
  icon: mdi:fridge
  button_action:
    tap_action:
      action: navigate
      navigation_path: '#kitchen'
- type: custom:room-summary-card
  area: dining_room
  navigate: '#kitchen'
```
