### ISSUE TITLE
Cutomize Mistake

### ISSUE THREAD

**Issue by kiloptero** [homeassistant-extras/room-summary-card#44]
Maybe its me, but I can't customize the card

type: custom:room-summary-card
area: escritorio_andres
entity: light.closet_escritorio
humidity_sensor: sensor.ikea_tvoc_humidity
temperature_sensor: sensor.ikea_tvoc_temperature
entities:
  - entity_id: climate.dormitorio_principal
  - entity_id: binary_sensor.ventana_escritorio_andres_contact
features:
  - hide_area_stats
grid_options:
  rows: 4
  columns: 5
customize:
  binary_sensor.ventana_escritorio_andres_contact:
    on_color: red
    off_color: blue

the idea is when on the binary sensor goes read and off blue
thanks

**Comment by warmfire540** [comment]
@kiloptero I have several cards that utilize on/off colors and on/off states.

instead of setting this info on the card, you set it on the entity itself.  You do this through customize yaml
- https://github.com/homeassistant-extras/room-summary-card/issues/32
- https://www.home-assistant.io/integrations/homeassistant/#manual-customization

here's an example of my customization files:
https://github.com/warmfire540/home-assistant-config-public/blob/home/customizations/entities/entities.yaml#L34

**Comment by kiloptero** [comment]
thanks, how yo associate the entities.yaml with the configuration. yaml?

Andres Roepke

**Comment by warmfire540** [comment]
@kiloptero you can directly edit your `configuration.yaml` and add your entities there like so:

```yaml
homeassistant:
  name: Home
  unit_system: metric
  # etc

  customize:
    # Add an entry for each entity that you want to overwrite.
    thermostat.family_room:
      on_color: blue
      off_color: red
  customize_domain:
    light:
      icon: mdi:home
  # Customize entities matching a pattern
  customize_glob:
    "light.kitchen_*":
      icon: mdi:description
    "scene.month_*_colors":
      icon: mdi:other
```

<img width="859" alt="Image" src="https://github.com/user-attachments/assets/c642c5d8-c203-4887-82d2-1d3ede667d9b" />

**Comment by kiloptero** [comment]
thanks.. how can i create a entity.yaml to consolidate every custom config
in other file? like sensors ?


you already make that;) thanks!!!!
Andres Roepke

**Comment by warmfire540** [comment]
ok so if you have made a separate entity.yaml already, you can include them into your main config like so
- probably you need only the first example since you may not be using globs or domain customizations `customize: !include_dir_merge_named ../yourfolder/entities`

```yaml
homeassistant:
  # Lets me customize individual entities
  customize: !include_dir_merge_named ../yourfolder/entities

  # Lets me customize all entities in a domain
  #  customize_domain: !include_dir_merge_named ../yourfolder/domains

  # Lets me customize entities based on a matching pattern
  # customize_glob: !include_dir_merge_named ../yourfolder/globs
```
