### ISSUE TITLE
Room Entity on_color replicated across all cards

### ISSUE THREAD

**Issue by benjycov** [homeassistant-extras/room-summary-card#61]
If you have two cards on the same dashboard:

```
- type: 'custom:room-summary-card'
  area: Living Room
  entity: 
    entity_id: input_boolean.living_room_in_use
    on_color: blue

- type: 'custom:room-summary-card'
  area: Kitchen
  entity: 
    entity_id: input_boolean.kitchen_in_use
    on_color: red
```
Then for both rooms the on_color will be blue.

I also tried using template binary_sensors rather than input_boolean, and for binary_sensors its seems on_color is ignored and they are yellow regardless.
