### ISSUE TITLE
Climate style shows cooling for heat-only thermostat when off

### ISSUE THREAD

**Issue by trevorswanson** [homeassistant-extras/room-summary-card#72]
I have a thermostat that only supports heat, but when the thermostat is turned off, my room summary card shows a cooling style.

<img width="268" alt="Image" src="https://github.com/user-attachments/assets/e15b4040-1c06-4c75-a0f4-3608a793c6ed" />

Here is the card
```yaml
type: custom:room-summary-card
area: basement
entities:
  - climate.basement_thermostat
sensors:
  - sensor.basement_thermostat_temperature
  - sensor.basement_thermostat_humidity
features:
  - hide_area_stats
grid_options:
  columns: 6
```

Here are the current attributes of `climate.basement_thermostat`:

```
hvac_modes: heat, off
min_temp: 50
max_temp: 90
preset_modes: none, eco
current_temperature: 63
temperature: null
current_humidity: 63
hvac_action: off
preset_mode: none
friendly_name: Basement Thermostat
supported_features: 401
```

Thermostats that support heat and cool do not show any style when off, for example:

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/87f7b870-c9dd-48c6-9203-f583e846c4da" />
