### ISSUE TITLE
Cannot show card colors and design

### ISSUE THREAD

**Issue by yasalmasri** [homeassistant-extras/room-summary-card#8]
Hi

Thanks for the awesome card and design it has.
I tried to implement it but it shows different design than what you have in the README and also I saw several posts they do have the same design as you.

Right now this is what I have: 
![Image](https://github.com/user-attachments/assets/5efd1178-4344-465f-b9eb-e08af09aad19)

this is the YAML of one of the cards:
```yaml
type: custom:room-summary-card
area: living_room
temperature_sensor: sensor.counts
humidity_sensor: sensor.counts
entities:
  - light.livingroom_lamp
  - switch.living_room_switch_left
  - switch.living_room_switch_right
navigate: /lovelace/living-room
grid_options:
  columns: 6

```

Even if I click on an entity to turn it on, it does not change the color, no circle background on each entity, neither the main entity has a circle background or color.

I followed the docs in the README but still cannot add the colors.

Rooms Summary Card version: 0.4.0
Home assistant version: 2025.2.1
