### ISSUE TITLE
[Feature Request] Room Occupancy

### ISSUE THREAD

**Issue by X1pheR** [homeassistant-extras/room-summary-card#83]
Would you be open for a feature request regarding room occupancy? I would like to be able to see if there is any occupancy in a room on the room card. Like a configurable card border color to indicate there is presence/occupancy in the room. Like you are already doing with the temperature/humidity.

However that would mean you can't see occupancy, humidity and temperature at the same time as they all would use the card border. However, I found someone who created a room card that uses the border of the room icon outline which would be nice; https://aguacatec.es/room-cards/#Bonus_Room_Cards_in_HACS

**Comment by warmfire540** [comment]
ooo that ring thing is cool.  
- can you show me what a presence sensor's state & attributes looks like in your dev tools?  one with and without detection?

i'll research a few options of how to visualize this (light card strobe, background, ring around icon, something else)

i'll ping some ideas or samples here

**Comment by X1pheR** [comment]
I thought you might 😉 They're just binary sensors for each area I turn on based on criteria. Like WASP in a box sensors, blueprint, mmwave sensor, media status, etc.

Just an idea. Perhaps do what that card does. Use the ring for environmental sensors like temp and humidity. And use the card border for presence. Making it a configurable color?

**Comment by X1pheR** [comment]
Just to show. This is how it looks like. I created template binary sensors with device class occupancy;

![Image](https://github.com/user-attachments/assets/22d22e38-cbd8-4b43-bf51-6e21edcbdfd0)

This is how the code looks like;
```
   # Slaapkamer
  - trigger:
      - platform: state
        entity_id: binary_sensor.slaapkamer_door_sensor_contact
        to: "on"
      - platform: state
        entity_id: binary_sensor.slaapkamer_door_sensor_contact
        to: "off"
        for:
          seconds: 20
      - platform: state
        entity_id: binary_sensor.slaapkamer_motion_sensor_occupancy
        to: "on"
    binary_sensor:
      - name: "Slaapkamer Bezet"
        unique_id: '32f7c30b-c362-4431-a7f1-c571b416e433'
        device_class: occupancy
        icon: mdi:account-box-outline
        state: >
          {{ is_state('binary_sensor.slaapkamer_door_sensor_contact', 'off') and is_state('binary_sensor.slaapkamer_motion_sensor_occupancy', 'on') }}
```

**Comment by Ltek** [comment]
Would be really nice to be able to 'light up' (user selected color) one or more of these when the room Motion Sensor detects occupancy... Card Border, Main Bubble Border, Main Bubble Icon Color

**Comment by warmfire540** [comment]
here's a very rough first stab.. potentially we can have
- animated / pulsing borders
- animated / breathing icon
- add icon borders.. icon fill color..

i'll work on cleaning it up.. and am open for ideas to make things pop more.  

https://github.com/user-attachments/assets/3c361c7d-4964-45d0-a89c-38f72f70f6e8

**Comment by Ltek** [comment]
WOW, nice!  Please allow for more than one Entity to be an Occupancy sensor. Some rooms are large enough to have 2 or 3. thx!

**Comment by X1pheR** [comment]
Wow! This is nice @warmfire540 . @Ltek also a good suggestion to support multiple entities. If supporting multiple entities perhaps making the section name more generic in stead of just Occupancy. Perhaps "Card Styling" or "Room Styling"?

**Comment by warmfire540** [comment]
@X1pheR this feature is specifically for occupancy and it's settings :/

for multiple entities it be something like below maybe.  i'll play with what features pop the most

```yaml
occupancy:
  entities:
    - binary_sensor.living_room_west_presence
    - binary_sensor.living_room_east_presence
  card_border_color:
    - 14
    - 221
    - 124
  icon_border_color:
    - 199
    - 52
    - 15
  icon_color:
    - 90
    - 121
    - 170
  icon_glow: true
  animation: true
```
