### ISSUE TITLE
Card title too large in some cases

### ISSUE THREAD

**Issue by warmfire540** [homeassistant-extras/room-summary-card#95]
![image](https://github.com/user-attachments/assets/46b82cfd-4c27-470a-9338-cfc23d7f6b86)

**Comment by LE-tarantino** [comment]
@warmfire540: What a killer release! Really appreciate the background feature!

However I am experiencing the same issue with the title and also - as it seems from your screenshots - no sensor icons are being displayed regardless of the new styles flag. Thridly the margin of the last entity icon seems to be off, maybe caused by the automatic resizing introduced. 

![Image](https://github.com/user-attachments/assets/8d1fbba8-602b-4987-976a-16a585753b2f)

```
type: custom:room-summary-card
sensors:
  - sensor.raumtemperatur_flur_eg
  - sensor.luftfeuchtigkeit_flur_eg
features:
  - skip_climate_styles
  - exclude_default_entities
  - hide_area_stats
  - skip_entity_styles
grid_options:
  columns: 6
  rows: auto
entities:
  - entity_id: switch.zentral_flur_eg
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    double_tap_action:
      action: none
    icon: mdi:image-filter-center-focus
  - entity_id: scene.verlassen
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    double_tap_action:
      action: none
  - entity_id: binary_sensor.aqara_turkontakt_eingang_eg_contact
    tap_action:
      action: more-info
    hold_action:
      action: more-info
    double_tap_action:
      action: none
  - entity_id: switch.prasenzmelder_flur_eg
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    double_tap_action:
      action: none
navigate: /lovelace/flur_eg
area: flur_eg
entity: switch.zentral_flur_eg
sensor_layout: default
```
